# Generated by Django 4.1 on 2022-12-06 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('idUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
                ('correo', models.EmailField(max_length=254)),
                ('celular', models.CharField(max_length=10)),
                ('ciudad', models.CharField(max_length=60)),
                ('contrasena', models.CharField(max_length=60)),
                ('imagen', models.ImageField(null=True, upload_to='imgUsuario')),
            ],
        ),
    ]
